version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  node-api:
    build: ./node-api
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    depends_on:
      redis:
        condition: service_healthy

  # provisioning-service:
  #   build: ./provisioning-service
  #   environment:
  #     - REDIS_ADDR=redis:6379
  #     - NODE_API_URL=http://node-api:8080
  #   depends_on:
  #     - redis
  #     - node-api

  user-simulator:
    build: ./user-simulator
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      redis:
        condition: service_healthy